  name: CICD

  on: workflow_dispatch:

  jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: Clone the code
          run: echo "Cloning the Code"
          
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Build using Docker
          run: echo "Building using Docker"
          
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Test the app
          run: echo "testing app"
          
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy the app
          run: echo "Deploying the app"
          
  
      
