# what is the goal of your workflow
# Goal: whenever someone changes the python code,
# the linter will check if the syntax, format, indentation (lint)
name: Auto Linter

on:

  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    # this will clone the code into runner
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7
#this will install python linter
      - name: pip install runner
        run: pip install ruff

      - name: check files for linting
        run: ruff check.
